version: "3.9"
# both production and development docker compose file
x-logging:
  &highlight-logging
    driver: fluentd
    options:
      fluentd-address: "otel.highlight.io:24224"
      fluentd-async: "true"
      fluentd-sub-second-precision: "true"
      tag: "highlight.project_id=memzo0pg"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile 
    restart: always
    volumes:
      - ~/data/plumephotos.com/images:/app/image
    ports: 
     - 3001:3001
    depends_on:
      - db
    logging: *highlight-logging
  
  caddy:
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    logging: *highlight-logging

  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    volumes:
     - ~/data/plumephotos.com/psql:/var/lib/postgresql/data/pgdata
    logging: *highlight-logging
