version: "3.9"
# both production and development docker compose file
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile 
    restart: always
    volumes:
      - ~/data/plumephotos.com/images:/app/image
    ports: 
     - 3001:3001
    depends_on:
      - db
  
  caddy:
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    volumes:
     - ~/data/plumephotos.com/psql:/var/lib/postgresql/data/pgdata
